FROM python:3.7-bullseye

WORKDIR /app

COPY requirements.txt .

RUN python3.7 -m pip install -r requirements.txt

# need crontab
COPY crontab/*.py crontab/
# and need the tests too
COPY tests/* crontab_tests/

# Note: needs access to Redis; assumes localhost:6879
CMD ["python3.7", "-m", "crontab_tests.test_crontab"]
