ARG PYTHON_VERSION="3.11"

FROM python:${PYTHON_VERSION}-bullseye
ARG PYTHON_VERSION
ARG PY="python${PYTHON_VERSION}"

ENV PYTHON_VERSION=$PYTHON_VERSION

WORKDIR /app

RUN ${PY} -m pip install --upgrade pip
COPY requirements_old.txt .
RUN ${PY} -m pip install -r requirements_old.txt

# need crontab
COPY crontab/*.py crontab/
# and need the tests too
COPY tests/* crontab_tests/

CMD ${PY} -m crontab_tests.test_crontab
